//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJChat.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IpBan
    {
        public long BanId { get; set; }
        public string BannedIp { get; set; }
        public string Username { get; set; }
        public System.DateTime BanTimestamp { get; set; }
        public System.DateTime BanEnd { get; set; }
    }
}
