//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJChat.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageLog
    {
        public long MessageId { get; set; }
        public System.DateTime UtcTimestamp { get; set; }
        public string UserName { get; set; }
        public string SourceIp { get; set; }
        public bool Blocked { get; set; }
        public string MessageText { get; set; }
    }
}
